#
# CD Pipeline: clone -> lint (flake8) -> tests (nose) -> build (buildah) -> deploy (openshift-client)
# Requires ClusterTasks: git-clone, buildah, openshift-client (see Makefile clustertasks)
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: main
    - name: build-image
      description: Full image URL for the built image (e.g. image-registry.../accounts:latest)
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: cleanup

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - init

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      runAfter:
        - clone

    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nose
      params:
        - name: DATABASE_URI
          value: "postgresql://postgres:postgres@postgresql:5432/postgres"
      runAfter:
        - clone

    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.build-image)
      runAfter:
        - lint
        - tests

    - name: deploy
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: deploy-accounts
      params:
        - name: build-image
          value: $(params.build-image)
      runAfter:
        - build
